name: Integration
on: push
jobs:
  integration:
    runs-on: self-hosted
    steps:
      - name: Check out repository code
        uses: actions/checkout@v2
      - name: Perform a Pester test from the Tests.ps1 file
        shell: pwsh
        run: |
          .\Invoke-PesterTests.ps1 -Username ${{ secrets.USERNAME }} -Secret ${{ secrets.SECRET }}